# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'dcs_code_injector_window_ui.ui'
##
## Created by: Qt User Interface Compiler version 6.5.3
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QGridLayout, QHBoxLayout, QMainWindow,
    QMenu, QMenuBar, QSizePolicy, QSplitter,
    QStatusBar, QTabWidget, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(981, 665)
        self.action_settings = QAction(MainWindow)
        self.action_settings.setObjectName(u"action_settings")
        self.action_clear_execution_file = QAction(MainWindow)
        self.action_clear_execution_file.setObjectName(u"action_clear_execution_file")
        self.action_clear_log = QAction(MainWindow)
        self.action_clear_log.setObjectName(u"action_clear_log")
        self.action_add_new_tab = QAction(MainWindow)
        self.action_add_new_tab.setObjectName(u"action_add_new_tab")
        self.action_search = QAction(MainWindow)
        self.action_search.setObjectName(u"action_search")
        self.action_copy_hook_file = QAction(MainWindow)
        self.action_copy_hook_file.setObjectName(u"action_copy_hook_file")
        self.action_increase_log_font_size = QAction(MainWindow)
        self.action_increase_log_font_size.setObjectName(u"action_increase_log_font_size")
        self.action_decrease_log_font_size = QAction(MainWindow)
        self.action_decrease_log_font_size.setObjectName(u"action_decrease_log_font_size")
        self.action_increase_code_font_size = QAction(MainWindow)
        self.action_increase_code_font_size.setObjectName(u"action_increase_code_font_size")
        self.action_decrease_code_font_size = QAction(MainWindow)
        self.action_decrease_code_font_size.setObjectName(u"action_decrease_code_font_size")
        self.action_back_up_settings_file = QAction(MainWindow)
        self.action_back_up_settings_file.setObjectName(u"action_back_up_settings_file")
        self.action_about = QAction(MainWindow)
        self.action_about.setObjectName(u"action_about")
        self.action_pick_log_font = QAction(MainWindow)
        self.action_pick_log_font.setObjectName(u"action_pick_log_font")
        self.action_pick_code_font = QAction(MainWindow)
        self.action_pick_code_font.setObjectName(u"action_pick_code_font")
        self.action_material_neon = QAction(MainWindow)
        self.action_material_neon.setObjectName(u"action_material_neon")
        self.action_fusion_dark = QAction(MainWindow)
        self.action_fusion_dark.setObjectName(u"action_fusion_dark")
        self.action_log_view_enabled = QAction(MainWindow)
        self.action_log_view_enabled.setObjectName(u"action_log_view_enabled")
        self.action_log_view_enabled.setCheckable(True)
        self.action_log_view_enabled.setChecked(True)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.gridLayout = QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(u"gridLayout")
        self.splitter = QSplitter(self.centralwidget)
        self.splitter.setObjectName(u"splitter")
        self.splitter.setOrientation(Qt.Vertical)
        self.horizontalLayoutWidget = QWidget(self.splitter)
        self.horizontalLayoutWidget.setObjectName(u"horizontalLayoutWidget")
        self.txt_log_layout = QHBoxLayout(self.horizontalLayoutWidget)
        self.txt_log_layout.setObjectName(u"txt_log_layout")
        self.txt_log_layout.setContentsMargins(0, 0, 0, 0)
        self.splitter.addWidget(self.horizontalLayoutWidget)
        self.tab_widget = QTabWidget(self.splitter)
        self.tab_widget.setObjectName(u"tab_widget")
        self.tab_widget.setAutoFillBackground(True)
        self.tab_widget.setTabsClosable(True)
        self.splitter.addWidget(self.tab_widget)

        self.gridLayout.addWidget(self.splitter, 0, 0, 1, 1)

        self.favorites_layout = QHBoxLayout()
        self.favorites_layout.setObjectName(u"favorites_layout")

        self.gridLayout.addLayout(self.favorites_layout, 1, 0, 1, 1)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 981, 22))
        self.menuFile = QMenu(self.menubar)
        self.menuFile.setObjectName(u"menuFile")
        self.menuTools = QMenu(self.menubar)
        self.menuTools.setObjectName(u"menuTools")
        self.menuView = QMenu(self.menubar)
        self.menuView.setObjectName(u"menuView")
        self.menuTheme = QMenu(self.menuView)
        self.menuTheme.setObjectName(u"menuTheme")
        self.menuHelp = QMenu(self.menubar)
        self.menuHelp.setObjectName(u"menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.menuFile.addAction(self.action_settings)
        self.menuFile.addAction(self.action_back_up_settings_file)
        self.menuTools.addAction(self.action_add_new_tab)
        self.menuTools.addSeparator()
        self.menuTools.addAction(self.action_clear_log)
        self.menuTools.addAction(self.action_search)
        self.menuTools.addSeparator()
        self.menuTools.addAction(self.action_copy_hook_file)
        self.menuView.addAction(self.action_log_view_enabled)
        self.menuView.addAction(self.action_increase_log_font_size)
        self.menuView.addAction(self.action_decrease_log_font_size)
        self.menuView.addAction(self.action_pick_log_font)
        self.menuView.addSeparator()
        self.menuView.addAction(self.action_increase_code_font_size)
        self.menuView.addAction(self.action_decrease_code_font_size)
        self.menuView.addAction(self.action_pick_code_font)
        self.menuView.addSeparator()
        self.menuView.addAction(self.menuTheme.menuAction())
        self.menuTheme.addAction(self.action_material_neon)
        self.menuTheme.addAction(self.action_fusion_dark)
        self.menuHelp.addAction(self.action_about)

        self.retranslateUi(MainWindow)

        self.tab_widget.setCurrentIndex(-1)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.action_settings.setText(QCoreApplication.translate("MainWindow", u"Settings", None))
        self.action_clear_execution_file.setText(QCoreApplication.translate("MainWindow", u"Clear execution file", None))
#if QT_CONFIG(shortcut)
        self.action_clear_execution_file.setShortcut(QCoreApplication.translate("MainWindow", u"Alt+X", None))
#endif // QT_CONFIG(shortcut)
        self.action_clear_log.setText(QCoreApplication.translate("MainWindow", u"Clear log", None))
#if QT_CONFIG(shortcut)
        self.action_clear_log.setShortcut(QCoreApplication.translate("MainWindow", u"Alt+L", None))
#endif // QT_CONFIG(shortcut)
        self.action_add_new_tab.setText(QCoreApplication.translate("MainWindow", u"Add new tab", None))
#if QT_CONFIG(shortcut)
        self.action_add_new_tab.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+N", None))
#endif // QT_CONFIG(shortcut)
        self.action_search.setText(QCoreApplication.translate("MainWindow", u"Search Log", None))
#if QT_CONFIG(shortcut)
        self.action_search.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+F", None))
#endif // QT_CONFIG(shortcut)
        self.action_copy_hook_file.setText(QCoreApplication.translate("MainWindow", u"Copy hook file", None))
        self.action_increase_log_font_size.setText(QCoreApplication.translate("MainWindow", u"Increase log font size", None))
#if QT_CONFIG(shortcut)
        self.action_increase_log_font_size.setShortcut(QCoreApplication.translate("MainWindow", u"Shift+Num++", None))
#endif // QT_CONFIG(shortcut)
        self.action_decrease_log_font_size.setText(QCoreApplication.translate("MainWindow", u"Decrease log font size", None))
#if QT_CONFIG(shortcut)
        self.action_decrease_log_font_size.setShortcut(QCoreApplication.translate("MainWindow", u"Shift+Num+-", None))
#endif // QT_CONFIG(shortcut)
        self.action_increase_code_font_size.setText(QCoreApplication.translate("MainWindow", u"Increase code font size", None))
#if QT_CONFIG(shortcut)
        self.action_increase_code_font_size.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl++", None))
#endif // QT_CONFIG(shortcut)
        self.action_decrease_code_font_size.setText(QCoreApplication.translate("MainWindow", u"Decrease code font size", None))
#if QT_CONFIG(shortcut)
        self.action_decrease_code_font_size.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+-", None))
#endif // QT_CONFIG(shortcut)
        self.action_back_up_settings_file.setText(QCoreApplication.translate("MainWindow", u"Back up settings file", None))
        self.action_about.setText(QCoreApplication.translate("MainWindow", u"About...", None))
        self.action_pick_log_font.setText(QCoreApplication.translate("MainWindow", u"Pick log font", None))
        self.action_pick_code_font.setText(QCoreApplication.translate("MainWindow", u"Pick code font", None))
        self.action_material_neon.setText(QCoreApplication.translate("MainWindow", u"Material Neon", None))
        self.action_fusion_dark.setText(QCoreApplication.translate("MainWindow", u"Fusion Dark", None))
        self.action_log_view_enabled.setText(QCoreApplication.translate("MainWindow", u"Log view enabled", None))
        self.menuFile.setTitle(QCoreApplication.translate("MainWindow", u"File", None))
        self.menuTools.setTitle(QCoreApplication.translate("MainWindow", u"Tools", None))
        self.menuView.setTitle(QCoreApplication.translate("MainWindow", u"View", None))
        self.menuTheme.setTitle(QCoreApplication.translate("MainWindow", u"Theme", None))
        self.menuHelp.setTitle(QCoreApplication.translate("MainWindow", u"Help", None))
    # retranslateUi

